apiVersion: apps/v1
kind: Deployment
metadata:
  name: issues
  labels:
    type: springboot
    module: issues
spec:
  selector:
    matchLabels:
      module: issues 
  template:
    metadata:
      labels:
        type: module
        access: external
        module: issues
    spec:
      containers:
        - name: issues
          image: dpokusa/issues:1.0-bytebay
          ports:
          - containerPort: 8080
          env:
          - name: LOG_APPENDER
            value: Console  
