apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels: 
    component: mongodb
    type: infrastructure
    access: internal
spec: 
  containers: 
    - image: mongo:3.7
      name: mongodb
      ports: 
        - containerPort: 27017

---

kind: Service
apiVersion: v1
metadata:
  name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  type: NodePort
  selector:
    component: mongodb

